server:
  port: 8081

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=ALBUMES;encrypt=true;trustServerCertificate=true
    username: sa
    password: AwesomePassword!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties:
      dialect: org.hibernate.dialect.SQLServer2012Dialect


